# Generated by Django 4.0.2 on 2022-02-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_article_date_creation_alter_article_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
